name: Development Workflow

on:
  push:
    branches: [DEV]

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  ORCH_URL: "https://staging.uipath.com"
  ORCH_TENANT: SagarSable
  ORCH_APP_ID: fb9a5e5c-bada-4dd8-aee3-a9144b601b41
  ORCH_APP_SECRET: 3a_oeu6fP2~0t%wH
  ORCH_ACC_NAME: UiPathTAMIndia
  ORCH_APP_SCOPES: "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines OR.Monitoring OR.Robots OR.Settings OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users"
  CLI_URL: "https://uipath.visualstudio.com/Public.Feeds/_artifacts/feed/UiPath-Official/NuGet/UiPath.CLI.Windows/overview/24.12.9166.24491"

jobs:
  Print-Environment-Variables:
    runs-on: [self-hosted, Windows, X64]
    #runs-on: self-hosted
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
#---------------------------------------------------------------------------------------        
#  cleaner:
#    needs: print-details
#    runs-on: [self-hosted, Windows, X64]
#    #runs-on: self-hosted
#    steps:
#      - name: Runner workspace path
#        shell: powershell
#        run: |
#          echo "Cleaning up previous run"
#          Remove-Item "${{ github.workspace }}" -Recurse -Force
#--------------------------------------------------------------------------------------
  Build-UiPath-NuGet-Package:
    # You should be able to run on windows 2019 or windows latest
    needs: Print-Environment-Variables
    runs-on: [self-hosted, Windows, X64]
    #runs-on: self-hosted
    steps: 
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
        uses: actions/checkout@v4
      - name: Build Nuget Package
        shell: powershell
        run:  ${{ github.workspace }}\Scripts\UiPathPack.ps1 ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package -autoVersion -cli_url ${{env.CLI_URL}}
      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
           package/*.*
           scripts/*.ps1
  #--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Publish-UiPath-Nuget-Package-DEV:
    needs: Build-UiPath-NuGet-Package
    runs-on: [self-hosted, Windows, X64]
    #runs-on: self-hosted
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Publish Nuget Package to DEV
        shell: powershell
        run: |
         ${{ github.workspace }}\scripts\UiPathDeploy.ps1 -packages_path ${{ github.workspace }}\package -orchestrator_url ${{env.ORCH_URL}} -orchestrator_tenant ${{env.ORCH_TENANT}} -UserKey ${{env.ORCH_APP_ID}}  -UserSecret ${{env.ORCH_APP_SECRET}} -account_name ${{env.ORCH_ACC_NAME}} -applicationscope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines OR.Monitoring OR.Robots OR.Settings OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users" -folder_organization_unit "Shared" -cli_url ${{env.CLI_URL}}

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Run-UiPath-Nuget-Package-DEV:
    needs: Publish-UiPath-Nuget-Package-DEV
    runs-on: [self-hosted, Windows, X64]
    #runs-on: self-hosted
    steps: 
      - name: Run-UiPath-Nuget-Package-DEV
        shell: powershell
        run: |
         ${{ github.workspace }}\scripts\UiPathJobRun.ps1 ${{ github.workspace }}\package\*.* -orchestrator_url ${{env.ORCH_URL}} -orchestrator_tenant ${{env.ORCH_TENANT}} -UserKey ${{env.ORCH_APP_ID}}  -UserSecret ${{env.ORCH_APP_SECRET}} -account_name ${{env.ORCH_ACC_NAME}} -applicationscope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines OR.Monitoring OR.Robots OR.Settings OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users" -folder_organization_unit "Shared" -cli_url ${{env.CLI_URL}}
