name: Development Workflow

on:
  push:
    branches: [DEV]

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  ORCH_URL: "https://staging.uipath.com"
  ORCH_TENANT: SagarSable
  ORCH_APP_ID: fb9a5e5c-bada-4dd8-aee3-a9144b601b41
  ORCH_APP_SECRET: 3a_oeu6fP2~0t%wH
  ORCH_ACC_NAME: UiPathTAMIndia
  ORCH_APP_SCOPES: OR.Administration OR.Administration.Read OR.Administration.Write OR.Analytics OR.Analytics.Read OR.Analytics.Write OR.Assets OR.Assets.Read OR.Assets.Write OR.Audit OR.Audit.Read OR.Audit.Write OR.BackgroundTasks OR.BackgroundTasks.Read OR.BackgroundTasks.Write OR.Execution OR.Execution.Read OR.Execution.Write OR.Folders OR.Folders.Read OR.Folders.Write OR.Hypervisor OR.Hypervisor.Read OR.Hypervisor.Write OR.Jobs OR.Jobs.Read OR.Jobs.Write OR.License OR.License.Read OR.License.Write OR.Machines OR.Machines.Read OR.Machines.Write OR.ML OR.ML.Read OR.ML.Write OR.Monitoring OR.Monitoring.Read OR.Monitoring.Write OR.Queues OR.Queues.Read OR.Queues.Write OR.Robots OR.Robots.Read OR.Robots.Write OR.Settings OR.Settings.Read OR.Settings.Write OR.Tasks OR.Tasks.Read OR.Tasks.Write OR.TestDataQueues OR.TestDataQueues.Read OR.TestDataQueues.Write OR.TestSetExecutions OR.TestSetExecutions.Read OR.TestSetExecutions.Write OR.TestSets OR.TestSets.Read OR.TestSets.Write OR.TestSetSchedules OR.TestSetSchedules.Read OR.TestSetSchedules.Write OR.Users OR.Users.Read OR.Users.Write OR.Webhooks OR.Webhooks.Read OR.Webhooks.Write
  CLI_URL: "https://uipath.visualstudio.com/Public.Feeds/_artifacts/feed/UiPath-Official/NuGet/UiPath.CLI.Windows/overview/24.12.9166.24491"

jobs:
  print-details:
    runs-on: [self-hosted, Windows, X64]
    #runs-on: self-hosted
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
#---------------------------------------------------------------------------------------        

#--------------------------------------------------------------------------------------
  build-uipath-nuget-package:
    # You should be able to run on windows 2019 or windows latest
    needs: print-details
    runs-on: [self-hosted, Windows, X64]
    #runs-on: self-hosted
    steps: 
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
        uses: actions/checkout@v4
      - name: Build Nuget Package
        shell: powershell
        run:  ${{ github.workspace }}\Scripts\UiPathPack.ps1 ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package -autoVersion -cli_url ${{env.CLI_URL}}
      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
           package/*.*
           scripts/*.ps1
  #--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  publish-uipath-nuget-package-Dev:
    needs: build-uipath-nuget-package
    runs-on: [self-hosted, Windows, X64]
    #runs-on: self-hosted
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Publish Nuget Package to DEV
        shell: powershell
        run: |
         ${{ github.workspace }}\scripts\UiPathDeploy.ps1 -packages_path ${{ github.workspace }}\package -orchestrator_url ${{env.ORCH_URL}} -orchestrator_tenant ${{env.ORCH_TENANT}} -applicationId ${{env.ORCH_APP_ID}}  -applicationSecret ${{env.ORCH_APP_SECRET}} -account_name ${{env.ORCH_ACC_NAME}} -applicationscope ${{env.ORCH_APP_SCOPES}} -folder_organization_unit "Shared" -cli_url ${{env.CLI_URL}}
