name: Development Workflow

on:
  push:
    branches:
      - DEV

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  ORCH_URL: "https://staging.uipath.com"
  ORCH_TENANT: SagarSable
  ORCH_CLIENT_ID: fb9a5e5c-bada-4dd8-aee3-a9144b601b41
  ORCH_USER_KEY: _mJ7U^!t8FWhe0Zs
  ORCH_ACC_NAME: uipathtamindia
  CLI_URL: "https://uipath.pkgs.visualstudio.com/Public.Feeds/_packaging/UiPath-Official/nuget/v3/flat2/UiPath.CLI.Windows/22.10.8438.32859/UiPath.CLI.Windows.22.10.8438.32859.nupkg"

jobs:
  print-details:
    runs-on: self-hosted
    #runs-on: self-hosted
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
  cleaner:
    runs-on: self-hosted
    #runs-on: self-hosted
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"

  build-uipath-nuget-package:
    # You should be able to run on windows 2019 or windows latest
    needs: cleaner
    runs-on: windows-latest
    #runs-on: self-hosted
    steps: 
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: Build Nuget Package
        shell: pwsh
        run:  ${{ github.workspace }}\scripts\UiPathPack.ps1 ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package -autoVersion -cli_url ${{env.CLI_URL}}
      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
           package/*.*
           scripts/*.ps1
  #--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  publish-uipath-nuget-package-Dev:
    needs: build-uipath-nuget-package
    runs-on: windows-latest
    #runs-on: self-hosted
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: Publish Nuget Package to DEV
        shell: pwsh
        run: |
         ${{ github.workspace }}\scripts\UiPathDeploy.ps1 -packages_path ${{ github.workspace }}\package -orchestrator_url ${{env.ORCH_URL}} ${{env.ORCH_TENANT}} -a ${{env.ORCH_ACC_NAME}} -I ${{env.ORCH_CLIENT_ID}}  -s ${{env.ORCH_USER_KEY}}  --applicationscope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines OR.Monitoring OR.Robots OR.Settings OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users" -o "Shared" -cli_url ${{env.CLI_URL}}
